version: '3.8'

services:
  backend:
    build: 
      context: ./EU_Back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./EU_Back/.env
    volumes:
      - ./EU_Back:/app
    restart: always

  frontend:
    build:
      context: ./EU_Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./EU_Front/.env
    depends_on:
      - backend
    restart: always
